/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function kmc_get_user_agent(): number;
export function kmc_get_app_instance_id(): number;
export function kmc_migrate_database(a: number): number;
export function kmc_import(a: number, b: number): number;
export function kmc_get_auth_context(a: number, b: number, c: number, d: number): number;
export function kmc_handle_url(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function kmc_embedded_confidential_oidc(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function kmc_export(a: number, b: number): number;
export function kmc_delete_profile(a: number, b: number): number;
export function kmc_create_profile(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): number;
export function kmc_create_pkce(): number;
export function kmc_cancel(): number;
export function kmc_all_credentials(a: number): number;
export function kmc_delete_credential(a: number, b: number): number;
export function kmc_list_credentials(a: number): number;
export function kmc_url_type(a: number, b: number): void;
export function ring_core_0_17_7_bn_mul_mont(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function wasm_bindgen__convert__closures__invoke0_mut__hfcbc7f02d7b2e907(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h6d330484440061e0(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__hd481a34b90376d27(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h3f3a53b263fcc69e(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h7dd4bce0c1368af6(a: number, b: number, c: number, d: number): void;
